from __future__ import annotations

from collections.abc import Callable, Sequence
from pathlib import Path

ScenarioFn = Callable[[str, Path], None]
Scenario = tuple[str, ScenarioFn]
ScenarioSource = Sequence[Scenario] | Callable[[], Sequence[Scenario]]


def load_scenarios(source: ScenarioSource | None = None) -> list[Scenario]:
    raw_source = source if source is not None else scenarios
    loaded = list(raw_source() if callable(raw_source) else raw_source)
    _validate_scenarios(loaded)
    return loaded


def scenario_index(*groups: Sequence[Scenario]) -> dict[str, ScenarioFn]:
    indexed: dict[str, ScenarioFn] = {}
    duplicate_labels: list[str] = []
    for group in groups:
        for label, fn in group:
            if label in indexed:
                duplicate_labels.append(label)
            indexed[label] = fn
    if duplicate_labels:
        raise ValueError(f"duplicate moved scenario labels: {', '.join(duplicate_labels)}")
    return indexed



def scenarios() -> list[Scenario]:
    from . import (
        install_uninstall,
        hook_config,
        view_peer,
        docs_contracts,
        send_enqueue,
        join_leave_attach,
        aggregate_wait_status,
        watchdog_alarm,
        cancel_message,
        pane_mode_delivery,
        daemon_core,
        interrupt,
        identity_recovery,
        clear_peer,
    )
    moved = scenario_index(
        install_uninstall.SCENARIOS,
        hook_config.SCENARIOS,
        view_peer.SCENARIOS,
        docs_contracts.SCENARIOS,
        send_enqueue.SCENARIOS,
        join_leave_attach.SCENARIOS,
        aggregate_wait_status.SCENARIOS,
        watchdog_alarm.SCENARIOS,
        cancel_message.SCENARIOS,
        pane_mode_delivery.SCENARIOS,
        daemon_core.SCENARIOS,
        interrupt.SCENARIOS,
        identity_recovery.SCENARIOS,
        clear_peer.SCENARIOS,
    )
    return [
        ('lifecycle_delivered_terminal', moved['lifecycle_delivered_terminal']),
        ('held_interrupt_does_not_block_delivery', moved['held_interrupt_does_not_block_delivery']),
        ('reserve_next_ignores_held_marker', moved['reserve_next_ignores_held_marker']),
        ('held_marker_persists_through_delivery', moved['held_marker_persists_through_delivery']),
        ('esc_fail_no_state_change', moved['esc_fail_no_state_change']),
        ('clear_hold_logs_event', moved['clear_hold_logs_event']),
        ('clear_hold_socket_still_pops_held', moved['clear_hold_socket_still_pops_held']),
        ('aggregate_interrupt_synthetic_reply', moved['aggregate_interrupt_synthetic_reply']),
        ('interrupt_pending_replacement_delivers', moved['interrupt_pending_replacement_delivers']),
        ('interrupt_new_replacement_after_interrupt_delivers', moved['interrupt_new_replacement_after_interrupt_delivers']),
        ('interrupt_claude_with_active_sends_esc_then_cc', moved['interrupt_claude_with_active_sends_esc_then_cc']),
        ('interrupt_codex_sends_only_esc', moved['interrupt_codex_sends_only_esc']),
        ('interrupt_unknown_type_falls_back_to_esc', moved['interrupt_unknown_type_falls_back_to_esc']),
        ('interrupt_claude_idle_skips_cc', moved['interrupt_claude_idle_skips_cc']),
        ('interrupt_claude_cc_failure_does_not_revert_state', moved['interrupt_claude_cc_failure_does_not_revert_state']),
        ('interrupt_key_dispatch_uses_target_lock_not_state_lock', moved['interrupt_key_dispatch_uses_target_lock_not_state_lock']),
        ('interrupt_no_try_deliver_between_keys', moved['interrupt_no_try_deliver_between_keys']),
        ('interrupt_endpoint_cache_apply_uses_state_lock', moved['interrupt_endpoint_cache_apply_uses_state_lock']),
        ('interrupt_waits_for_same_target_delivery_touch', moved['interrupt_waits_for_same_target_delivery_touch']),
        ('interrupt_env_override_disables_cc', moved['interrupt_env_override_disables_cc']),
        ('interrupt_key_delay_env_nonfinite_uses_default', moved['interrupt_key_delay_env_nonfinite_uses_default']),
        ('interrupt_key_delay_env_clamps_out_of_range', moved['interrupt_key_delay_env_clamps_out_of_range']),
        ('claude_interrupt_keys_invalid_uses_default', moved['claude_interrupt_keys_invalid_uses_default']),
        ('claude_interrupt_keys_empty_uses_default', moved['claude_interrupt_keys_empty_uses_default']),
        ('send_interrupt_key_timeout_returns_false', moved['send_interrupt_key_timeout_returns_false']),
        ('clear_hold_clears_interrupt_partial_failure_gate', moved['clear_hold_clears_interrupt_partial_failure_gate']),
        ('interrupt_double_within_no_active_skips_cc', moved['interrupt_double_within_no_active_skips_cc']),
        ('interrupt_double_with_fresh_delivery_sends_cc_again', moved['interrupt_double_with_fresh_delivery_sends_cc_again']),
        ('interrupt_peer_cli_exit_nonzero_on_partial_key_failure', moved['interrupt_peer_cli_exit_nonzero_on_partial_key_failure']),
        ('interrupt_peer_action_text_and_json_modes', moved['interrupt_peer_action_text_and_json_modes']),
        ('interrupt_peer_clear_hold_text_and_json_modes', moved['interrupt_peer_clear_hold_text_and_json_modes']),
        ('interrupt_peer_status_json_unchanged_and_json_rejected', moved['interrupt_peer_status_json_unchanged_and_json_rejected']),
        ('interrupted_late_prompt_submitted_before_replacement', moved['interrupted_late_prompt_submitted_before_replacement']),
        ('interrupted_late_prompt_submitted_after_replacement', moved['interrupted_late_prompt_submitted_after_replacement']),
        ('interrupted_late_turn_stop_preserves_replacement', moved['interrupted_late_turn_stop_preserves_replacement']),
        ('interrupted_no_turn_stop_no_context_suppressed', moved['interrupted_no_turn_stop_no_context_suppressed']),
        ('interrupted_no_turn_race_routes_replacement_then_suppresses_old', moved['interrupted_no_turn_race_routes_replacement_then_suppresses_old']),
        ('interrupted_inflight_tombstone_retains_on_unrelated_stop', moved['interrupted_inflight_tombstone_retains_on_unrelated_stop']),
        ('interrupted_empty_values_do_not_match_tombstone', moved['interrupted_empty_values_do_not_match_tombstone']),
        ('interrupted_tombstone_current_ctx_id_match_cleans', moved['interrupted_tombstone_current_ctx_id_match_cleans']),
        ('interrupted_tombstone_current_ctx_turn_match_cleans', moved['interrupted_tombstone_current_ctx_turn_match_cleans']),
        ('interrupted_tombstone_stale_stop_preserves_replacement_watchdog', moved['interrupted_tombstone_stale_stop_preserves_replacement_watchdog']),
        ('interrupted_tombstone_aggregate_ctx_does_not_cancel_aggregate_watchdog', moved['interrupted_tombstone_aggregate_ctx_does_not_cancel_aggregate_watchdog']),
        ('aggregate_late_real_stop_after_interrupt_does_not_overwrite', moved['aggregate_late_real_stop_after_interrupt_does_not_overwrite']),
        ('watchdog_cancel_on_empty_response', moved['watchdog_cancel_on_empty_response']),
        ('alarm_cancelled_by_qualifying_request', moved['alarm_cancelled_by_qualifying_request']),
        ('socket_path_alarm_cancel', moved['socket_path_alarm_cancel']),
        ('response_send_guard_socket_request_notice', moved['response_send_guard_socket_request_notice']),
        ('response_send_guard_socket_force_and_other_peer', moved['response_send_guard_socket_force_and_other_peer']),
        ('response_send_guard_socket_no_auto_return_allowed', moved['response_send_guard_socket_no_auto_return_allowed']),
        ('response_send_guard_socket_atomic_multi', moved['response_send_guard_socket_atomic_multi']),
        ('response_send_guard_socket_aggregate_and_held', moved['response_send_guard_socket_aggregate_and_held']),
        ('response_send_guard_after_response_finished_allowed', moved['response_send_guard_after_response_finished_allowed']),
        ('fallback_path_alarm_cancel', moved['fallback_path_alarm_cancel']),
        ('ingressing_not_delivered_before_finalize', moved['ingressing_not_delivered_before_finalize']),
        ('replay_does_not_cancel_later_alarm', moved['replay_does_not_cancel_later_alarm']),
        ('ingress_finalize_alarm_cancel_watchdog_lock_atomic', moved['ingress_finalize_alarm_cancel_watchdog_lock_atomic']),
        ('bridge_origin_fallback_ingressing_promoted', moved['bridge_origin_fallback_ingressing_promoted']),
        ('socket_normalizes_non_ingressing_status', moved['socket_normalizes_non_ingressing_status']),
        ('aggregate_fallback_finalize', moved['aggregate_fallback_finalize']),
        ('aged_ingressing_promoted_by_maintenance', moved['aged_ingressing_promoted_by_maintenance']),
        ('aged_ingressing_does_not_cancel_alarms', moved['aged_ingressing_does_not_cancel_alarms']),
        ('aged_ingressing_malformed_timestamp_promoted', moved['aged_ingressing_malformed_timestamp_promoted']),
        ('fresh_ingressing_not_promoted_by_maintenance', moved['fresh_ingressing_not_promoted_by_maintenance']),
        ('alarm_not_cancelled_by_result', moved['alarm_not_cancelled_by_result']),
        ('alarm_not_cancelled_by_bridge', moved['alarm_not_cancelled_by_bridge']),
        ('user_prompt_does_not_cancel_alarm', moved['user_prompt_does_not_cancel_alarm']),
        ('extend_wait_upserts_watchdog', moved['extend_wait_upserts_watchdog']),
        ('extend_wait_aggregate_rejected', moved['extend_wait_aggregate_rejected']),
        ('extend_wait_unknown_message', moved['extend_wait_unknown_message']),
        ('extend_wait_terminal_tombstone_classification', moved['extend_wait_terminal_tombstone_classification']),
        ('extend_wait_pending_rejected', moved['extend_wait_pending_rejected']),
        ('extend_wait_not_owner', moved['extend_wait_not_owner']),
        ('cancel_message_pending_removes_row', moved['cancel_message_pending_removes_row']),
        ('cancel_message_inflight_pre_paste', moved['cancel_message_inflight_pre_paste']),
        ('cancel_message_pane_mode_deferred_inflight_cancellable', moved['cancel_message_pane_mode_deferred_inflight_cancellable']),
        ('cancel_message_inflight_after_enter_rejects_with_interrupt_guidance', moved['cancel_message_inflight_after_enter_rejects_with_interrupt_guidance']),
        ('cancel_message_submitted_rejects_with_interrupt_guidance', moved['cancel_message_submitted_rejects_with_interrupt_guidance']),
        ('cancel_message_delivered_rejects_with_interrupt_guidance', moved['cancel_message_delivered_rejects_with_interrupt_guidance']),
        ('cancel_message_ownership_violation', moved['cancel_message_ownership_violation']),
        ('cancel_message_idempotent_after_terminal', moved['cancel_message_idempotent_after_terminal']),
        ('cancel_message_aggregate_per_leg_keeps_other_legs', moved['cancel_message_aggregate_per_leg_keeps_other_legs']),
        ('cancel_message_action_text_and_json_modes', moved['cancel_message_action_text_and_json_modes']),
        ('cancel_message_action_error_text_modes', moved['cancel_message_action_error_text_modes']),
        ('aggregate_status_open_from_queue_and_reply', moved['aggregate_status_open_from_queue_and_reply']),
        ('aggregate_status_zero_reply_from_queue', moved['aggregate_status_zero_reply_from_queue']),
        ('aggregate_status_cancelled_and_timeout_synthetic_reasons', moved['aggregate_status_cancelled_and_timeout_synthetic_reasons']),
        ('aggregate_status_legacy_synthetic_reply_uses_tombstone', moved['aggregate_status_legacy_synthetic_reply_uses_tombstone']),
        ('aggregate_status_foreign_and_unknown_indistinguishable', moved['aggregate_status_foreign_and_unknown_indistinguishable']),
        ('aggregate_status_source_conflict_fails_closed', moved['aggregate_status_source_conflict_fails_closed']),
        ('aggregate_status_legacy_fallback_and_cap', moved['aggregate_status_legacy_fallback_and_cap']),
        ('aggregate_status_watchdog_only_anchor', moved['aggregate_status_watchdog_only_anchor']),
        ('wait_status_empty_self_view', moved['wait_status_empty_self_view']),
        ('wait_status_uses_watchdog_snapshot', moved['wait_status_uses_watchdog_snapshot']),
        ('wait_status_outstanding_watchdogs_alarms_pending_inbound', moved['wait_status_outstanding_watchdogs_alarms_pending_inbound']),
        ('wait_status_aggregate_waits_privacy_and_completed_result', moved['wait_status_aggregate_waits_privacy_and_completed_result']),
        ('wait_status_caps_and_summary_counts', moved['wait_status_caps_and_summary_counts']),
        ('delivery_watchdog_arms_on_reserve', moved['delivery_watchdog_arms_on_reserve']),
        ('delivery_watchdog_fire_inflight_notice', moved['delivery_watchdog_fire_inflight_notice']),
        ('watchdog_fire_after_terminal_suppresses_notice', moved['watchdog_fire_after_terminal_suppresses_notice']),
        ('pending_watchdog_wake_removed_on_terminal', moved['pending_watchdog_wake_removed_on_terminal']),
        ('delivery_watchdog_extend_replaces_wake', moved['delivery_watchdog_extend_replaces_wake']),
        ('delivery_watchdog_submitted_extend_and_text', moved['delivery_watchdog_submitted_extend_and_text']),
        ('delivery_watchdog_aggregate_pending_extend_rejected', moved['delivery_watchdog_aggregate_pending_extend_rejected']),
        ('delivery_watchdog_replaced_by_response_on_delivered', moved['delivery_watchdog_replaced_by_response_on_delivered']),
        ('delivery_watchdog_requeue_cancels', moved['delivery_watchdog_requeue_cancels']),
        ('delivery_watchdog_mark_pending_cancels', moved['delivery_watchdog_mark_pending_cancels']),
        ('delivery_watchdog_pane_mode_reverts_cancel', moved['delivery_watchdog_pane_mode_reverts_cancel']),
        ('delivery_watchdog_phase_mismatch_skipped', moved['delivery_watchdog_phase_mismatch_skipped']),
        ('watchdog_phase_legacy_default_response', moved['watchdog_phase_legacy_default_response']),
        ('delivery_watchdog_aggregate_leg_coexists_with_response', moved['delivery_watchdog_aggregate_leg_coexists_with_response']),
        ('delivery_watchdog_aggregate_interrupt_cancels_leg_only', moved['delivery_watchdog_aggregate_interrupt_cancels_leg_only']),
        ('aggregate_response_watchdog_text_uses_progress', moved['aggregate_response_watchdog_text_uses_progress']),
        ('aggregate_completion_suppresses_pending_watchdog_wake', moved['aggregate_completion_suppresses_pending_watchdog_wake']),
        ('aggregate_completion_lock_order_spies', moved['aggregate_completion_lock_order_spies']),
        ('aggregate_store_update_hook_installed', moved['aggregate_store_update_hook_installed']),
        ('watchdog_fire_snapshot_pop_skips_superseded_wake', moved['watchdog_fire_snapshot_pop_skips_superseded_wake']),
        ('watchdog_fire_final_revalidation_after_terminal_cleanup', moved['watchdog_fire_final_revalidation_after_terminal_cleanup']),
        ('duplicate_enqueue_does_not_cancel_alarm', moved['duplicate_enqueue_does_not_cancel_alarm']),
        ('alarm_op_invalid_delay_is_rejected', moved['alarm_op_invalid_delay_is_rejected']),
        ('send_peer_watchdog_negative_one_rejected', moved['send_peer_watchdog_negative_one_rejected']),
        ('send_peer_watchdog_nan_rejected', moved['send_peer_watchdog_nan_rejected']),
        ('send_peer_watchdog_inf_rejected', moved['send_peer_watchdog_inf_rejected']),
        ('send_peer_watchdog_minus_inf_rejected', moved['send_peer_watchdog_minus_inf_rejected']),
        ('send_peer_watchdog_zero_disables_for_request', moved['send_peer_watchdog_zero_disables_for_request']),
        ('send_peer_watchdog_finite_positive_succeeds', moved['send_peer_watchdog_finite_positive_succeeds']),
        ('send_peer_no_auto_return_explicit_watchdog_rejected', moved['send_peer_no_auto_return_explicit_watchdog_rejected']),
        ('send_peer_no_auto_return_watchdog_zero_succeeds', moved['send_peer_no_auto_return_watchdog_zero_succeeds']),
        ('send_peer_no_auto_return_invalid_watchdog_value_precedence', moved['send_peer_no_auto_return_invalid_watchdog_value_precedence']),
        ('send_peer_no_auto_return_skips_default_watchdog', moved['send_peer_no_auto_return_skips_default_watchdog']),
        ('send_peer_auto_return_default_watchdog_still_attaches', moved['send_peer_auto_return_default_watchdog_still_attaches']),
        ('send_peer_no_auto_return_broadcast_watchdog_rejected', moved['send_peer_no_auto_return_broadcast_watchdog_rejected']),
        ('send_peer_watchdog_inf_with_notice_reports_finite_error_first', moved['send_peer_watchdog_inf_with_notice_reports_finite_error_first']),
        ('send_peer_watchdog_zero_with_notice_still_rejects_request_only', moved['send_peer_watchdog_zero_with_notice_still_rejects_request_only']),
        ('send_peer_watchdog_abc_argparse_error', moved['send_peer_watchdog_abc_argparse_error']),
        ('extend_wait_zero_negative_nan_inf_rejected', moved['extend_wait_zero_negative_nan_inf_rejected']),
        ('extend_wait_finite_positive_calls_request_extend', moved['extend_wait_finite_positive_calls_request_extend']),
        ('extend_wait_terminal_error_texts', moved['extend_wait_terminal_error_texts']),
        ('wait_status_cli_summary_and_json', moved['wait_status_cli_summary_and_json']),
        ('wait_status_cli_unsupported_old_daemon', moved['wait_status_cli_unsupported_old_daemon']),
        ('wait_status_cli_rejects_inactive_sender', moved['wait_status_cli_rejects_inactive_sender']),
        ('aggregate_status_cli_summary_and_json', moved['aggregate_status_cli_summary_and_json']),
        ('aggregate_status_cli_unsupported_and_not_found_text', moved['aggregate_status_cli_unsupported_and_not_found_text']),
        ('aggregate_status_cli_rejects_inactive_sender', moved['aggregate_status_cli_rejects_inactive_sender']),
        ('alarm_negative_nan_inf_minus_inf_rejected', moved['alarm_negative_nan_inf_minus_inf_rejected']),
        ('alarm_zero_and_finite_positive_call_request_alarm', moved['alarm_zero_and_finite_positive_call_request_alarm']),
        ('alarm_request_failure_prints_no_success_hint', moved['alarm_request_failure_prints_no_success_hint']),
        ('alarm_request_retries_timeout_with_stable_wake_id', moved['alarm_request_retries_timeout_with_stable_wake_id']),
        ('alarm_request_retry_exhaustion_is_bounded', moved['alarm_request_retry_exhaustion_is_bounded']),
        ('alarm_request_retries_lock_wait_with_stable_wake_id', moved['alarm_request_retries_lock_wait_with_stable_wake_id']),
        ('alarm_request_lock_wait_retry_exhaustion_is_bounded', moved['alarm_request_lock_wait_retry_exhaustion_is_bounded']),
        ('alarm_request_non_retryable_daemon_error_is_immediate', moved['alarm_request_non_retryable_daemon_error_is_immediate']),
        ('alarm_request_rejects_mismatched_daemon_wake_id', moved['alarm_request_rejects_mismatched_daemon_wake_id']),
        ('resolve_default_watchdog_seconds_env_table', moved['resolve_default_watchdog_seconds_env_table']),
        ('daemon_socket_alarm_op_rejects_non_finite', moved['daemon_socket_alarm_op_rejects_non_finite']),
        ('daemon_socket_alarm_op_idempotent_wake_id', moved['daemon_socket_alarm_op_idempotent_wake_id']),
        ('daemon_socket_alarm_op_rejects_invalid_conflicting_wake_id', moved['daemon_socket_alarm_op_rejects_invalid_conflicting_wake_id']),
        ('daemon_socket_alarm_op_idempotent_after_cancelled_or_fired', moved['daemon_socket_alarm_op_idempotent_after_cancelled_or_fired']),
        ('daemon_socket_extend_watchdog_op_rejects_non_finite', moved['daemon_socket_extend_watchdog_op_rejects_non_finite']),
        ('daemon_upsert_message_watchdog_rejects_non_finite', moved['daemon_upsert_message_watchdog_rejects_non_finite']),
        ('daemon_enqueue_rejects_no_auto_return_watchdog_atomically', moved['daemon_enqueue_rejects_no_auto_return_watchdog_atomically']),
        ('daemon_enqueue_no_auto_return_watchdog_zero_normalized', moved['daemon_enqueue_no_auto_return_watchdog_zero_normalized']),
        ('daemon_prior_hint_pending_cancel', moved['daemon_prior_hint_pending_cancel']),
        ('daemon_prior_hint_delivered_interrupt', moved['daemon_prior_hint_delivered_interrupt']),
        ('daemon_prior_hint_inflight_pane_mode_cancel', moved['daemon_prior_hint_inflight_pane_mode_cancel']),
        ('daemon_prior_hint_inflight_after_enter_interrupt', moved['daemon_prior_hint_inflight_after_enter_interrupt']),
        ('daemon_prior_hint_terminal_or_absent_no_hint', moved['daemon_prior_hint_terminal_or_absent_no_hint']),
        ('daemon_prior_hint_rejections_have_no_hints', moved['daemon_prior_hint_rejections_have_no_hints']),
        ('daemon_prior_hint_aggregate_suffix', moved['daemon_prior_hint_aggregate_suffix']),
        ('daemon_prior_hint_notice_safe_wording', moved['daemon_prior_hint_notice_safe_wording']),
        ('daemon_prior_hint_same_pair_only', moved['daemon_prior_hint_same_pair_only']),
        ('daemon_prior_hint_multi_target_partial', moved['daemon_prior_hint_multi_target_partial']),
        ('daemon_prior_hint_current_prompt_only', moved['daemon_prior_hint_current_prompt_only']),
        ('daemon_prior_hint_active_ctx_beats_pending_queue_row', moved['daemon_prior_hint_active_ctx_beats_pending_queue_row']),
        ('prior_hint_classifier_drift_invariant', moved['prior_hint_classifier_drift_invariant']),
        ('delivery_pre_touch_failure_requeues_and_cancel_removes', moved['delivery_pre_touch_failure_requeues_and_cancel_removes']),
        ('delivery_post_touch_failure_requires_interrupt', moved['delivery_post_touch_failure_requires_interrupt']),
        ('delivery_post_touch_pre_enter_cancel_rejects', moved['delivery_post_touch_pre_enter_cancel_rejects']),
        ('delivery_unrelated_target_progress_during_blocked_tmux', moved['delivery_unrelated_target_progress_during_blocked_tmux']),
        ('daemon_upsert_no_auto_return_watchdog_rejected', moved['daemon_upsert_no_auto_return_watchdog_rejected']),
        ('daemon_register_alarm_rejects_non_finite_and_negative', moved['daemon_register_alarm_rejects_non_finite_and_negative']),
        ('daemon_mark_message_delivered_ignores_non_finite_watchdog', moved['daemon_mark_message_delivered_ignores_non_finite_watchdog']),
        ('daemon_no_auto_return_watchdog_arm_guard_strips', moved['daemon_no_auto_return_watchdog_arm_guard_strips']),
        ('daemon_no_auto_return_watchdog_ingress_sanitizers', moved['daemon_no_auto_return_watchdog_ingress_sanitizers']),
        ('daemon_socket_ack_message_unsupported_does_not_delete_queue', moved['daemon_socket_ack_message_unsupported_does_not_delete_queue']),
        ('daemon_ack_message_helper_removed', moved['daemon_ack_message_helper_removed']),
        ('stale_watchdog_skipped', moved['stale_watchdog_skipped']),
        ('alarm_fire_text_includes_rearm_hint', moved['alarm_fire_text_includes_rearm_hint']),
        ('watchdog_pending_text_omits_held_interrupt', moved['watchdog_pending_text_omits_held_interrupt']),
        ('pane_mode_pending_defers_without_attempt', moved['pane_mode_pending_defers_without_attempt']),
        ('pane_mode_clears_then_delivers', moved['pane_mode_clears_then_delivers']),
        ('pane_mode_force_cancel_after_grace', moved['pane_mode_force_cancel_after_grace']),
        ('pane_mode_nonforce_mode_stays_pending', moved['pane_mode_nonforce_mode_stays_pending']),
        ('pane_mode_busy_target_does_not_start_timer', moved['pane_mode_busy_target_does_not_start_timer']),
        ('retry_enter_skips_pane_mode', moved['retry_enter_skips_pane_mode']),
        ('pane_mode_probe_failure_defers_pending', moved['pane_mode_probe_failure_defers_pending']),
        ('pane_mode_force_cancel_failure_stays_pending', moved['pane_mode_force_cancel_failure_stays_pending']),
        ('enter_deferred_survives_stale_requeue_and_restart', moved['enter_deferred_survives_stale_requeue_and_restart']),
        ('pre_enter_probe_failure_defers_enter', moved['pre_enter_probe_failure_defers_enter']),
        ('pane_mode_grace_zero_disables_cancel', moved['pane_mode_grace_zero_disables_cancel']),
        ('wait_for_probe_retries_enter_with_pane_id', moved['wait_for_probe_retries_enter_with_pane_id']),
        ('wait_for_probe_no_retry_without_pane_id', moved['wait_for_probe_no_retry_without_pane_id']),
        ('detached_leave_explicit_cleanup', moved['detached_leave_explicit_cleanup']),
        ('detached_leave_no_notice_when_only_inactive_remain', moved['detached_leave_no_notice_when_only_inactive_remain']),
        ('detached_join_same_alias_same_pane', moved['detached_join_same_alias_same_pane']),
        ('detached_join_same_alias_different_pane', moved['detached_join_same_alias_different_pane']),
        ('detached_join_different_alias_same_pane_allowed', moved['detached_join_different_alias_same_pane_allowed']),
        ('active_join_same_alias_still_rejected', moved['active_join_same_alias_still_rejected']),
        ('join_blank_status_same_pane_still_rejected', moved['join_blank_status_same_pane_still_rejected']),
        ('join_other_session_pane_lock_still_rejected', moved['join_other_session_pane_lock_still_rejected']),
        ('join_probe_passes_pane_id_to_wait', moved['join_probe_passes_pane_id_to_wait']),
        ('bridge_attach_start_daemon_argv_includes_from_start', moved['bridge_attach_start_daemon_argv_includes_from_start']),
        ('bridge_daemon_ctl_start_subparser_accepts_from_start', moved['bridge_daemon_ctl_start_subparser_accepts_from_start']),
        ('daemon_command_forwards_from_start', moved['daemon_command_forwards_from_start']),
        ('daemon_command_ignores_legacy_max_hops', moved['daemon_command_ignores_legacy_max_hops']),
        ('bridge_daemon_ctl_subcommands_reject_max_hops', moved['bridge_daemon_ctl_subcommands_reject_max_hops']),
        ('bridge_daemon_rejects_max_hops_cli', moved['bridge_daemon_rejects_max_hops_cli']),
        ('bridge_daemon_ctl_start_argv_includes_from_start_end_to_end', moved['bridge_daemon_ctl_start_argv_includes_from_start_end_to_end']),
        ('daemon_follow_from_start_replays_prompt_submitted', moved['daemon_follow_from_start_replays_prompt_submitted']),
        ('daemon_follow_from_start_false_skips_pre_existing_record', moved['daemon_follow_from_start_false_skips_pre_existing_record']),
        ('daemon_follow_from_start_handles_self_daemon_started_safely', moved['daemon_follow_from_start_handles_self_daemon_started_safely']),
        ('orphan_nonce_in_user_prompt', moved['orphan_nonce_in_user_prompt']),
        ('prompt_intercept_request_notice_body', moved['prompt_intercept_request_notice_body']),
        ('prompt_intercept_bridge_notice_no_source_notice', moved['prompt_intercept_bridge_notice_no_source_notice']),
        ('prompt_intercept_response_guard_queue_allows', moved['prompt_intercept_response_guard_queue_allows']),
        ('prompt_intercept_mixed_inflight_requeues', moved['prompt_intercept_mixed_inflight_requeues']),
        ('prompt_submitted_duplicate_noop', moved['prompt_submitted_duplicate_noop']),
        ('prompt_submitted_duplicate_without_nonce_noop', moved['prompt_submitted_duplicate_without_nonce_noop']),
        ('prompt_intercept_aggregate_completes', moved['prompt_intercept_aggregate_completes']),
        ('prompt_intercept_held_drain_noop', moved['prompt_intercept_held_drain_noop']),
        ('held_drain_stale_stop_preserves_new_ctx', moved['held_drain_stale_stop_preserves_new_ctx']),
        ('held_drain_missing_identity_does_not_clear_active_ctx', moved['held_drain_missing_identity_does_not_clear_active_ctx']),
        ('held_drain_matching_prior_id_without_turn_still_clears_ctx', moved['held_drain_matching_prior_id_without_turn_still_clears_ctx']),
        ('stale_hold_ignored_active_context_routes_normally', moved['stale_hold_ignored_active_context_routes_normally']),
        ('stale_hold_old_stop_with_active_ctx_applies_a4_mismatch', moved['stale_hold_old_stop_with_active_ctx_applies_a4_mismatch']),
        ('held_no_prior_id_with_active_ctx_classified_stale', moved['held_no_prior_id_with_active_ctx_classified_stale']),
        ('held_matching_prior_id_turn_id_mismatch_falls_through_to_a4', moved['held_matching_prior_id_turn_id_mismatch_falls_through_to_a4']),
        ('held_with_no_context_drain_still_works', moved['held_with_no_context_drain_still_works']),
        ('held_matching_prior_id_with_matching_turn_drain_still_works', moved['held_matching_prior_id_with_matching_turn_drain_still_works']),
        ('held_with_interrupted_tombstone_match_classify_first', moved['held_with_interrupted_tombstone_match_classify_first']),
        ('aggregate_leg_unaffected_by_held_marker', moved['aggregate_leg_unaffected_by_held_marker']),
        ('prompt_intercept_inflight_only_requeues', moved['prompt_intercept_inflight_only_requeues']),
        ('consume_once_basic', moved['consume_once_basic']),
        ('consume_once_empty_response', moved['consume_once_empty_response']),
        ('empty_response_whitespace_only_routes_sentinel', moved['empty_response_whitespace_only_routes_sentinel']),
        ('empty_response_preserves_nonempty_with_surrounding_whitespace', moved['empty_response_preserves_nonempty_with_surrounding_whitespace']),
        ('empty_response_self_return_still_skipped', moved['empty_response_self_return_still_skipped']),
        ('empty_response_auto_return_false_still_skipped', moved['empty_response_auto_return_false_still_skipped']),
        ('empty_response_inactive_requester_still_skipped', moved['empty_response_inactive_requester_still_skipped']),
        ('empty_response_unicode_whitespace_routes_sentinel', moved['empty_response_unicode_whitespace_routes_sentinel']),
        ('nonce_mismatch_fail_closed', moved['nonce_mismatch_fail_closed']),
        ('no_observed_nonce_with_candidate_fail_closed', moved['no_observed_nonce_with_candidate_fail_closed']),
        ('daemon_restart_queue_scan', moved['daemon_restart_queue_scan']),
        ('daemon_reload_inflight_idempotent', moved['daemon_reload_inflight_idempotent']),
        ('ambiguous_inflight_fail_closed', moved['ambiguous_inflight_fail_closed']),
        ('stale_reserved_orphan_swept', moved['stale_reserved_orphan_swept']),
        ('held_drain_skips_consume_once', moved['held_drain_skips_consume_once']),
        ('matching_nonce_contaminated_body_residual', moved['matching_nonce_contaminated_body_residual']),
        ('aggregate_consume_once_no_overwrite', moved['aggregate_consume_once_no_overwrite']),
        ('empty_response_in_aggregate_path_unchanged', moved['empty_response_in_aggregate_path_unchanged']),
        ('nonce_mismatch_stops_enter_retry', moved['nonce_mismatch_stops_enter_retry']),
        ('nonce_missing_stops_enter_retry', moved['nonce_missing_stops_enter_retry']),
        ('hook_logger_anchored_regex', moved['hook_logger_anchored_regex']),
        ('turn_id_mismatch_preserves_ctx', moved['turn_id_mismatch_preserves_ctx']),
        ('turn_id_mismatch_annotation_is_idempotent', moved['turn_id_mismatch_annotation_is_idempotent']),
        ('turn_id_mismatch_matching_stop_before_expiry_cleans_normally', moved['turn_id_mismatch_matching_stop_before_expiry_cleans_normally']),
        ('turn_id_mismatch_expiry_unblocks_target', moved['turn_id_mismatch_expiry_unblocks_target']),
        ('turn_id_mismatch_expiry_waits_for_watchdog_deadline', moved['turn_id_mismatch_expiry_waits_for_watchdog_deadline']),
        ('turn_id_mismatch_watchdog_fire_preserves_post_grace', moved['turn_id_mismatch_watchdog_fire_preserves_post_grace']),
        ('turn_id_mismatch_aggregate_watchdog_fire_preserves_post_grace', moved['turn_id_mismatch_aggregate_watchdog_fire_preserves_post_grace']),
        ('turn_id_mismatch_post_watchdog_grace_zero_allows_same_tick_expiry', moved['turn_id_mismatch_post_watchdog_grace_zero_allows_same_tick_expiry']),
        ('turn_id_mismatch_extend_wait_before_fire_defers_without_stamp', moved['turn_id_mismatch_extend_wait_before_fire_defers_without_stamp']),
        ('turn_id_mismatch_expiry_does_not_remove_non_delivered_queue_rows', moved['turn_id_mismatch_expiry_does_not_remove_non_delivered_queue_rows']),
        ('turn_id_mismatch_aggregate_leg_expiry_no_synthetic_reply', moved['turn_id_mismatch_aggregate_leg_expiry_no_synthetic_reply']),
        ('turn_id_mismatch_sweep_no_op_without_annotation', moved['turn_id_mismatch_sweep_no_op_without_annotation']),
        ('turn_id_mismatch_sweep_no_op_after_normal_pop', moved['turn_id_mismatch_sweep_no_op_after_normal_pop']),
        ('turn_id_mismatch_notice_ctx_follows_same_expiry', moved['turn_id_mismatch_notice_ctx_follows_same_expiry']),
        ('short_id_format', moved['short_id_format']),
        ('resolve_targets_single', moved['resolve_targets_single']),
        ('resolve_targets_multi_basic', moved['resolve_targets_multi_basic']),
        ('resolve_targets_order_preserved', moved['resolve_targets_order_preserved']),
        ('resolve_targets_dedup', moved['resolve_targets_dedup']),
        ('resolve_targets_strip_empties', moved['resolve_targets_strip_empties']),
        ('resolve_targets_reserved_alone', moved['resolve_targets_reserved_alone']),
        ('resolve_targets_reserved_mix_rejected', moved['resolve_targets_reserved_mix_rejected']),
        ('resolve_targets_unknown_rejected', moved['resolve_targets_unknown_rejected']),
        ('resolve_targets_sender_in_list_rejected', moved['resolve_targets_sender_in_list_rejected']),
        ('resolve_targets_empty_after_strip_rejected', moved['resolve_targets_empty_after_strip_rejected']),
        ('aggregate_trigger_request_multi', moved['aggregate_trigger_request_multi']),
        ('aggregate_trigger_single_no', moved['aggregate_trigger_single_no']),
        ('aggregate_trigger_notice_no', moved['aggregate_trigger_notice_no']),
        ('aggregate_trigger_bridge_sender_no', moved['aggregate_trigger_bridge_sender_no']),
        ('aggregate_trigger_no_auto_return_no', moved['aggregate_trigger_no_auto_return_no']),
        ('enqueue_aggregate_metadata_modes', moved['enqueue_aggregate_metadata_modes']),
        ('prune_keeps_recent_n', moved['prune_keeps_recent_n']),
        ('prune_disabled_retention_zero', moved['prune_disabled_retention_zero']),
        ('prune_below_retention', moved['prune_below_retention']),
        ('prune_missing_forgotten_dir_safe', moved['prune_missing_forgotten_dir_safe']),
        ('resolve_forgotten_retention_invalid_env', moved['resolve_forgotten_retention_invalid_env']),
        ('queue_status_counts', moved['queue_status_counts']),
        ('queue_status_counts_missing_file', moved['queue_status_counts_missing_file']),
        ('uninstall_helper_print_paths', moved['uninstall_helper_print_paths']),
        ('uninstall_helper_refuses_dangerous_path', moved['uninstall_helper_refuses_dangerous_path']),
        ('uninstall_sh_dry_run_invokes_hook_helper_with_dry_run', moved['uninstall_sh_dry_run_invokes_hook_helper_with_dry_run']),
        ('uninstall_sh_non_dry_run_removes_hook_entries', moved['uninstall_sh_non_dry_run_removes_hook_entries']),
        ('uninstall_sh_keep_hooks_skips_helper_under_dry_run', moved['uninstall_sh_keep_hooks_skips_helper_under_dry_run']),
        ('uninstall_sh_hook_helper_failure_aborts', moved['uninstall_sh_hook_helper_failure_aborts']),
        ('direct_exec_targets_executable', moved['direct_exec_targets_executable']),
        ('healthcheck_executable_helper_distinguishes_states', moved['healthcheck_executable_helper_distinguishes_states']),
        ('python_env_override_removed_from_tracked_files', moved['python_env_override_removed_from_tracked_files']),
        ('install_sh_python_version_gate', moved['install_sh_python_version_gate']),
        ('bridge_healthcheck_sh_python_version_gate', moved['bridge_healthcheck_sh_python_version_gate']),
        ('install_sh_chmods_target_or_fails', moved['install_sh_chmods_target_or_fails']),
        ('install_sh_default_updates_shell_rc', moved['install_sh_default_updates_shell_rc']),
        ('install_sh_shell_rc_dry_run_and_opt_out', moved['install_sh_shell_rc_dry_run_and_opt_out']),
        ('install_sh_shell_rc_target_selection', moved['install_sh_shell_rc_target_selection']),
        ('install_sh_shell_rc_backup_and_path_short_circuit', moved['install_sh_shell_rc_backup_and_path_short_circuit']),
        ('install_sh_shell_quotes_bin_dir_metacharacters', moved['install_sh_shell_quotes_bin_dir_metacharacters']),
        ('install_sh_shell_rc_replaces_existing_marker_block', moved['install_sh_shell_rc_replaces_existing_marker_block']),
        ('install_sh_claude_editor_mode_missing_skips', moved['install_sh_claude_editor_mode_missing_skips']),
        ('install_sh_claude_editor_mode_updates_with_backup', moved['install_sh_claude_editor_mode_updates_with_backup']),
        ('install_sh_claude_editor_mode_updates_global_and_settings', moved['install_sh_claude_editor_mode_updates_global_and_settings']),
        ('install_sh_claude_editor_mode_missing_global_updates_settings', moved['install_sh_claude_editor_mode_missing_global_updates_settings']),
        ('install_sh_claude_editor_mode_invalid_global_still_updates_settings', moved['install_sh_claude_editor_mode_invalid_global_still_updates_settings']),
        ('install_sh_claude_editor_mode_normal_noop', moved['install_sh_claude_editor_mode_normal_noop']),
        ('install_sh_claude_editor_mode_absent_adds_root', moved['install_sh_claude_editor_mode_absent_adds_root']),
        ('install_sh_claude_editor_mode_invalid_json_skips', moved['install_sh_claude_editor_mode_invalid_json_skips']),
        ('install_sh_claude_editor_mode_invalid_utf8_skips', moved['install_sh_claude_editor_mode_invalid_utf8_skips']),
        ('install_sh_claude_editor_mode_bom_skips', moved['install_sh_claude_editor_mode_bom_skips']),
        ('install_sh_claude_editor_mode_non_object_skips', moved['install_sh_claude_editor_mode_non_object_skips']),
        ('install_sh_claude_editor_mode_dry_run_no_write', moved['install_sh_claude_editor_mode_dry_run_no_write']),
        ('install_sh_claude_editor_mode_preserves_mode', moved['install_sh_claude_editor_mode_preserves_mode']),
        ('install_sh_claude_editor_mode_symlink_preserved', moved['install_sh_claude_editor_mode_symlink_preserved']),
        ('install_sh_claude_editor_mode_nested_root_absent_warns_skips', moved['install_sh_claude_editor_mode_nested_root_absent_warns_skips']),
        ('install_sh_claude_editor_mode_nested_with_root_warns_updates_root_only', moved['install_sh_claude_editor_mode_nested_with_root_warns_updates_root_only']),
        ('install_sh_claude_editor_mode_skip_flag_no_write', moved['install_sh_claude_editor_mode_skip_flag_no_write']),
        ('install_sh_claude_editor_mode_broken_symlink_warns', moved['install_sh_claude_editor_mode_broken_symlink_warns']),
        ('install_sh_claude_editor_mode_concurrent_change_aborts', moved['install_sh_claude_editor_mode_concurrent_change_aborts']),
        ('install_sh_hook_failure_hard_fails', moved['install_sh_hook_failure_hard_fails']),
        ('install_sh_hook_failure_ignore_flag_allows_success', moved['install_sh_hook_failure_ignore_flag_allows_success']),
        ('install_sh_hook_dry_run_failure_hard_fails', moved['install_sh_hook_dry_run_failure_hard_fails']),
        ('install_sh_hook_success_succeeds', moved['install_sh_hook_success_succeeds']),
        ('install_sh_shim_failure_still_hard_fails_under_override', moved['install_sh_shim_failure_still_hard_fails_under_override']),
        ('install_sh_skip_hooks_with_ignore_flag_is_noop', moved['install_sh_skip_hooks_with_ignore_flag_is_noop']),
        ('bridge_install_hooks_rejects_malformed_json_without_overwrite', moved['bridge_install_hooks_rejects_malformed_json_without_overwrite']),
        ('bridge_install_hooks_rejects_non_object_json_without_overwrite', moved['bridge_install_hooks_rejects_non_object_json_without_overwrite']),
        ('bridge_install_hooks_dry_run_invalid_json_fails_without_overwrite', moved['bridge_install_hooks_dry_run_invalid_json_fails_without_overwrite']),
        ('bridge_install_hooks_missing_json_still_creates', moved['bridge_install_hooks_missing_json_still_creates']),
        ('bridge_install_hooks_invalid_utf8_fails_without_overwrite', moved['bridge_install_hooks_invalid_utf8_fails_without_overwrite']),
        ('bridge_install_hooks_existing_valid_json_object_merges_correctly', moved['bridge_install_hooks_existing_valid_json_object_merges_correctly']),
        ('bridge_install_hooks_codex_hooks_rejects_malformed_json_without_overwrite', moved['bridge_install_hooks_codex_hooks_rejects_malformed_json_without_overwrite']),
        ('bridge_install_hooks_codex_config_ignores_nested_codex_hooks', moved['bridge_install_hooks_codex_config_ignores_nested_codex_hooks']),
        ('bridge_install_hooks_codex_config_ignores_nested_disable_paste_burst', moved['bridge_install_hooks_codex_config_ignores_nested_disable_paste_burst']),
        ('bridge_install_hooks_codex_config_updates_only_scoped_keys', moved['bridge_install_hooks_codex_config_updates_only_scoped_keys']),
        ('bridge_install_hooks_codex_config_inserts_features_key_before_next_table', moved['bridge_install_hooks_codex_config_inserts_features_key_before_next_table']),
        ('bridge_install_hooks_codex_config_dry_run_no_write', moved['bridge_install_hooks_codex_config_dry_run_no_write']),
        ('bridge_install_hooks_codex_config_empty_features_section_inserts', moved['bridge_install_hooks_codex_config_empty_features_section_inserts']),
        ('bridge_install_hooks_codex_config_first_table_is_array_table', moved['bridge_install_hooks_codex_config_first_table_is_array_table']),
        ('bridge_install_hooks_codex_config_table_header_with_trailing_comment', moved['bridge_install_hooks_codex_config_table_header_with_trailing_comment']),
        ('bridge_install_hooks_codex_config_commented_out_assignments_ignored', moved['bridge_install_hooks_codex_config_commented_out_assignments_ignored']),
        ('bridge_install_hooks_codex_config_no_trailing_newline_handled', moved['bridge_install_hooks_codex_config_no_trailing_newline_handled']),
        ('bridge_install_hooks_codex_config_already_enabled_is_byte_unchanged', moved['bridge_install_hooks_codex_config_already_enabled_is_byte_unchanged']),
        ('codex_config_marker_records_and_uninstall_restores_updated_values', moved['codex_config_marker_records_and_uninstall_restores_updated_values']),
        ('codex_config_marker_records_inserted_keys_and_uninstall_removes_them', moved['codex_config_marker_records_inserted_keys_and_uninstall_removes_them']),
        ('codex_config_missing_created_by_install_removed_on_uninstall_when_bridge_only', moved['codex_config_missing_created_by_install_removed_on_uninstall_when_bridge_only']),
        ('codex_config_already_enabled_keys_create_no_marker', moved['codex_config_already_enabled_keys_create_no_marker']),
        ('codex_config_reinstall_preserves_original_marker', moved['codex_config_reinstall_preserves_original_marker']),
        ('codex_config_user_changed_after_install_is_not_clobbered', moved['codex_config_user_changed_after_install_is_not_clobbered']),
        ('codex_config_dry_run_install_writes_no_marker_or_config', moved['codex_config_dry_run_install_writes_no_marker_or_config']),
        ('codex_config_dry_run_uninstall_with_marker_writes_no_config_or_marker', moved['codex_config_dry_run_uninstall_with_marker_writes_no_config_or_marker']),
        ('codex_config_skip_codex_does_not_touch_config_or_marker', moved['codex_config_skip_codex_does_not_touch_config_or_marker']),
        ('codex_config_uninstall_with_malformed_marker_aborts_clean', moved['codex_config_uninstall_with_malformed_marker_aborts_clean']),
        ('codex_config_uninstall_with_unknown_marker_version_aborts', moved['codex_config_uninstall_with_unknown_marker_version_aborts']),
        ('codex_config_uninstall_with_marker_path_mismatch_aborts', moved['codex_config_uninstall_with_marker_path_mismatch_aborts']),
        ('codex_config_uninstall_with_unknown_flag_key_aborts', moved['codex_config_uninstall_with_unknown_flag_key_aborts']),
        ('codex_config_uninstall_with_invalid_operation_aborts', moved['codex_config_uninstall_with_invalid_operation_aborts']),
        ('codex_config_uninstall_with_updated_missing_original_line_aborts', moved['codex_config_uninstall_with_updated_missing_original_line_aborts']),
        ('codex_config_marker_write_failure_aborts_before_config_write', moved['codex_config_marker_write_failure_aborts_before_config_write']),
        ('codex_config_inserted_features_section_with_user_added_keys_keeps_section', moved['codex_config_inserted_features_section_with_user_added_keys_keeps_section']),
        ('codex_config_existing_empty_config_records_existed_true_and_uninstall_keeps_it', moved['codex_config_existing_empty_config_records_existed_true_and_uninstall_keeps_it']),
        ('codex_config_marker_normalized_path_accepts_equivalent_path', moved['codex_config_marker_normalized_path_accepts_equivalent_path']),
        ('restart_dry_run_no_side_effect', moved['restart_dry_run_no_side_effect']),
        ('recover_orphan_delivered', moved['recover_orphan_delivered']),
        ('recover_orphan_delivered_aggregate_member', moved['recover_orphan_delivered_aggregate_member']),
        ('prune_concurrent_stat_safe', moved['prune_concurrent_stat_safe']),
        ('format_peer_list_model_safe_default', moved['format_peer_list_model_safe_default']),
        ('format_peer_list_full_includes_operator_fields', moved['format_peer_list_full_includes_operator_fields']),
        ('bridge_manage_summary_concise', moved['bridge_manage_summary_concise']),
        ('bridge_manage_summary_defaults', moved['bridge_manage_summary_defaults']),
        ('bridge_manage_summary_legacy_state_fallback', moved['bridge_manage_summary_legacy_state_fallback']),
        ('bridge_manage_summary_missing_session_exits', moved['bridge_manage_summary_missing_session_exits']),
        ('model_safe_participants_strips_endpoints', moved['model_safe_participants_strips_endpoints']),
        ('model_safe_participants_uses_active_only', moved['model_safe_participants_uses_active_only']),
        ('list_peers_json_daemon_status_strips_pid', moved['list_peers_json_daemon_status_strips_pid']),
        ('view_peer_rejects_snapshot_without_snapshot_mode', moved['view_peer_rejects_snapshot_without_snapshot_mode']),
        ('view_peer_rejects_page_with_since_last_or_search', moved['view_peer_rejects_page_with_since_last_or_search']),
        ('view_peer_allows_page_in_live_onboard_older_and_snapshot_in_older_search', moved['view_peer_allows_page_in_live_onboard_older_and_snapshot_in_older_search']),
        ('view_peer_rejects_empty_search_before_session_lookup', moved['view_peer_rejects_empty_search_before_session_lookup']),
        ('view_peer_empty_search_counts_as_search_for_mode_errors', moved['view_peer_empty_search_counts_as_search_for_mode_errors']),
        ('view_peer_nonempty_search_still_reaches_validation', moved['view_peer_nonempty_search_still_reaches_validation']),
        ('view_peer_search_with_page_after_a19_reports_page_error', moved['view_peer_search_with_page_after_a19_reports_page_error']),
        ('view_peer_doc_surfaces_disclose_search_semantics', moved['view_peer_doc_surfaces_disclose_search_semantics']),
        ('interrupt_peer_doc_surfaces_disclose_no_op_race', moved['interrupt_peer_doc_surfaces_disclose_no_op_race']),
        ('interrupt_peer_doc_surfaces_no_queued_active_directive', moved['interrupt_peer_doc_surfaces_no_queued_active_directive']),
        ('prompt_intercepted_doc_surfaces_disclose_user_typing_collision', moved['prompt_intercepted_doc_surfaces_disclose_user_typing_collision']),
        ('response_send_guard_doc_surfaces_are_precise', moved['response_send_guard_doc_surfaces_are_precise']),
        ('probe_prompt_is_compact_quickstart', moved['probe_prompt_is_compact_quickstart']),
        ('send_peer_wait_doc_surfaces_name_blocking_consequence', moved['send_peer_wait_doc_surfaces_name_blocking_consequence']),
        ('watchdog_phase_doc_surfaces_are_consistent', moved['watchdog_phase_doc_surfaces_are_consistent']),
        ('wait_status_doc_surfaces_anti_polling', moved['wait_status_doc_surfaces_anti_polling']),
        ('aggregate_status_doc_surfaces_leg_level_and_anti_polling', moved['aggregate_status_doc_surfaces_leg_level_and_anti_polling']),
        ('view_peer_render_output_model_safe', moved['view_peer_render_output_model_safe']),
        ('view_peer_search_explicit_snapshot_uses_safe_ref', moved['view_peer_search_explicit_snapshot_uses_safe_ref']),
        ('view_peer_snapshot_ref_collision_unique', moved['view_peer_snapshot_ref_collision_unique']),
        ('view_peer_capture_errors_sanitized', moved['view_peer_capture_errors_sanitized']),
        ('view_peer_snapshot_not_found_hides_full_id', moved['view_peer_snapshot_not_found_hides_full_id']),
        ('view_peer_since_last_matches_changed_volatile_chrome', moved['view_peer_since_last_matches_changed_volatile_chrome']),
        ('view_peer_since_last_legacy_tail_derives_stable_anchor', moved['view_peer_since_last_legacy_tail_derives_stable_anchor']),
        ('view_peer_since_last_ambiguous_current_anchor_skips_to_unique', moved['view_peer_since_last_ambiguous_current_anchor_skips_to_unique']),
        ('view_peer_since_last_matches_anchor_before_long_delta', moved['view_peer_since_last_matches_anchor_before_long_delta']),
        ('view_peer_since_last_build_rejects_duplicate_previous_window', moved['view_peer_since_last_build_rejects_duplicate_previous_window']),
        ('view_peer_since_last_uncertain_does_not_advance_cursor', moved['view_peer_since_last_uncertain_does_not_advance_cursor']),
        ('view_peer_since_last_upgrade_reset_when_no_legacy_anchor', moved['view_peer_since_last_upgrade_reset_when_no_legacy_anchor']),
        ('view_peer_since_last_low_info_lines_do_not_anchor', moved['view_peer_since_last_low_info_lines_do_not_anchor']),
        ('view_peer_since_last_claude_status_variants_are_volatile', moved['view_peer_since_last_claude_status_variants_are_volatile']),
        ('view_peer_since_last_status_classifier_preserves_prose', moved['view_peer_since_last_status_classifier_preserves_prose']),
        ('view_peer_since_last_claude_status_lines_do_not_anchor', moved['view_peer_since_last_claude_status_lines_do_not_anchor']),
        ('view_peer_since_last_filters_stored_volatile_anchor_lines', moved['view_peer_since_last_filters_stored_volatile_anchor_lines']),
        ('view_peer_since_last_skips_shortened_stored_anchor_that_fails_quality', moved['view_peer_since_last_skips_shortened_stored_anchor_that_fails_quality']),
        ('view_peer_since_last_volatile_only_claude_status_delta', moved['view_peer_since_last_volatile_only_claude_status_delta']),
        ('view_peer_since_last_codex_status_variants_preserved', moved['view_peer_since_last_codex_status_variants_preserved']),
        ('view_peer_since_last_volatile_only_delta', moved['view_peer_since_last_volatile_only_delta']),
        ('view_peer_since_last_short_delta_consumed_once', moved['view_peer_since_last_short_delta_consumed_once']),
        ('view_peer_since_last_request_plus_short_reply_consumed_after_cursor_update', moved['view_peer_since_last_request_plus_short_reply_consumed_after_cursor_update']),
        ('view_peer_since_last_consumed_tail_does_not_hide_new_duplicate', moved['view_peer_since_last_consumed_tail_does_not_hide_new_duplicate']),
        ('view_peer_since_last_consumed_tail_anchor_change_resets', moved['view_peer_since_last_consumed_tail_anchor_change_resets']),
        ('view_peer_since_last_consumed_tail_mismatch_clears', moved['view_peer_since_last_consumed_tail_mismatch_clears']),
        ('view_peer_since_last_consumed_tail_cap', moved['view_peer_since_last_consumed_tail_cap']),
        ('view_peer_since_last_consumed_tail_ignores_volatile_churn', moved['view_peer_since_last_consumed_tail_ignores_volatile_churn']),
        ('view_peer_since_last_codex_prompt_placeholder_not_anchor', moved['view_peer_since_last_codex_prompt_placeholder_not_anchor']),
        ('view_peer_since_last_filters_stored_codex_prompt_placeholder_anchor', moved['view_peer_since_last_filters_stored_codex_prompt_placeholder_anchor']),
        ('view_peer_since_last_preserves_codex_bridge_prompt_lines', moved['view_peer_since_last_preserves_codex_bridge_prompt_lines']),
        ('view_peer_since_last_preserves_trailing_semantic_codex_arrow', moved['view_peer_since_last_preserves_trailing_semantic_codex_arrow']),
        ('view_peer_since_last_preserves_semantic_codex_arrow_before_footer', moved['view_peer_since_last_preserves_semantic_codex_arrow_before_footer']),
        ('view_peer_since_last_claude_partial_status_fragments_are_volatile', moved['view_peer_since_last_claude_partial_status_fragments_are_volatile']),
        ('view_peer_since_last_partial_status_preserves_prose', moved['view_peer_since_last_partial_status_preserves_prose']),
        ('endpoint_rejects_stale_pane_lock_without_live', moved['endpoint_rejects_stale_pane_lock_without_live']),
        ('endpoint_rejects_same_pane_new_live_identity', moved['endpoint_rejects_same_pane_new_live_identity']),
        ('endpoint_probe_unknown_does_not_mutate', moved['endpoint_probe_unknown_does_not_mutate']),
        ('endpoint_accepts_matching_process_fingerprint', moved['endpoint_accepts_matching_process_fingerprint']),
        ('backfill_refuses_to_mint_without_live_record', moved['backfill_refuses_to_mint_without_live_record']),
        ('backfill_refuses_other_live_identity', moved['backfill_refuses_other_live_identity']),
        ('backfill_rejects_changed_process_fingerprint', moved['backfill_rejects_changed_process_fingerprint']),
        ('backfill_allows_fresh_hook_proof_create', moved['backfill_allows_fresh_hook_proof_create']),
        ('backfill_fresh_probe_repairs_unscoped_live_mismatch', moved['backfill_fresh_probe_repairs_unscoped_live_mismatch']),
        ('unscoped_hook_canonicalizes_via_pane_lock', moved['unscoped_hook_canonicalizes_via_pane_lock']),
        ('unscoped_hook_canonicalizes_during_attach_gap', moved['unscoped_hook_canonicalizes_during_attach_gap']),
        ('unscoped_hook_canonicalizes_via_attached_registry', moved['unscoped_hook_canonicalizes_via_attached_registry']),
        ('unscoped_hook_new_process_fails_closed', moved['unscoped_hook_new_process_fails_closed']),
        ('unscoped_hook_cross_reboot_fails_closed', moved['unscoped_hook_cross_reboot_fails_closed']),
        ('unscoped_hook_missing_prior_fingerprint_fails_closed', moved['unscoped_hook_missing_prior_fingerprint_fails_closed']),
        ('unscoped_hook_different_agent_fails_closed', moved['unscoped_hook_different_agent_fails_closed']),
        ('unscoped_hook_same_session_no_canonicalization_event', moved['unscoped_hook_same_session_no_canonicalization_event']),
        ('scoped_different_session_no_canonicalization', moved['scoped_different_session_no_canonicalization']),
        ('session_ended_payload_mismatch_no_canonicalization', moved['session_ended_payload_mismatch_no_canonicalization']),
        ('resolver_reconnects_exact_mismatch_shape', moved['resolver_reconnects_exact_mismatch_shape']),
        ('hook_reconnects_exact_mismatch_shape', moved['hook_reconnects_exact_mismatch_shape']),
        ('cross_pane_candidate_mismatch_blocks_reconnect', moved['cross_pane_candidate_mismatch_blocks_reconnect']),
        ('codex1_incident_replay_canonicalizes_repeated_unscoped_hooks', moved['codex1_incident_replay_canonicalizes_repeated_unscoped_hooks']),
        ('target_recovery_reconnects_stale_pane_by_codex_transcript', moved['target_recovery_reconnects_stale_pane_by_codex_transcript']),
        ('target_recovery_blocks_transcript_session_mismatch', moved['target_recovery_blocks_transcript_session_mismatch']),
        ('target_recovery_blocks_missing_transcript', moved['target_recovery_blocks_missing_transcript']),
        ('target_recovery_blocks_wrong_pid_transcript', moved['target_recovery_blocks_wrong_pid_transcript']),
        ('target_recovery_blocks_different_agent_at_target', moved['target_recovery_blocks_different_agent_at_target']),
        ('target_recovery_blocks_same_pane_target', moved['target_recovery_blocks_same_pane_target']),
        ('target_recovery_blocks_unresolvable_target', moved['target_recovery_blocks_unresolvable_target']),
        ('target_recovery_skips_without_participant_target', moved['target_recovery_skips_without_participant_target']),
        ('target_recovery_read_purpose_does_not_mutate', moved['target_recovery_read_purpose_does_not_mutate']),
        ('target_recovery_env_disable_blocks', moved['target_recovery_env_disable_blocks']),
        ('tmux_display_pane_empty_metadata_is_unavailable', moved['tmux_display_pane_empty_metadata_is_unavailable']),
        ('codex_rollout_path_regex_is_strict', moved['codex_rollout_path_regex_is_strict']),
        ('target_recovery_only_matching_alias_recovers', moved['target_recovery_only_matching_alias_recovers']),
        ('hook_unknown_preserves_verified_process_identity', moved['hook_unknown_preserves_verified_process_identity']),
        ('probe_tmux_access_failure_unknown', moved['probe_tmux_access_failure_unknown']),
        ('endpoint_read_mismatch_does_not_mutate', moved['endpoint_read_mismatch_does_not_mutate']),
        ('verified_candidate_ordering_prefers_pane_then_newest', moved['verified_candidate_ordering_prefers_pane_then_newest']),
        ('resume_new_pane_reconnects_unknown_old_and_logs', moved['resume_new_pane_reconnects_unknown_old_and_logs']),
        ('resume_unknown_old_opt_out_blocks_switch', moved['resume_unknown_old_opt_out_blocks_switch']),
        ('hook_cached_prior_unknown_does_not_reconnect', moved['hook_cached_prior_unknown_does_not_reconnect']),
        ('resolver_reconnects_to_alternate_verified_live_record', moved['resolver_reconnects_to_alternate_verified_live_record']),
        ('resolver_candidate_unknown_on_final_probe_does_not_reconnect', moved['resolver_candidate_unknown_on_final_probe_does_not_reconnect']),
        ('resolver_read_reconnect_logs_distinct_reason', moved['resolver_read_reconnect_logs_distinct_reason']),
        ('session_end_replacement_uses_verified_candidate', moved['session_end_replacement_uses_verified_candidate']),
        ('reconnect_rereads_mapping_before_write', moved['reconnect_rereads_mapping_before_write']),
        ('caller_reconnects_from_resumed_pane', moved['caller_reconnects_from_resumed_pane']),
        ('no_probe_requires_verified_live_identity', moved['no_probe_requires_verified_live_identity']),
        ('daemon_undeliverable_request_returns_result', moved['daemon_undeliverable_request_returns_result']),
        ('interrupt_endpoint_lost_finalizes_delivered_non_aggregate', moved['interrupt_endpoint_lost_finalizes_delivered_non_aggregate']),
        ('interrupt_endpoint_lost_finalizes_delivered_aggregate', moved['interrupt_endpoint_lost_finalizes_delivered_aggregate']),
        ('retry_enter_endpoint_lost_does_not_press_enter', moved['retry_enter_endpoint_lost_does_not_press_enter']),
        ('direct_notices_suppress_unverified_endpoint', moved['direct_notices_suppress_unverified_endpoint']),
        ('view_peer_unverified_endpoint_uses_daemon_not_local_capture', moved['view_peer_unverified_endpoint_uses_daemon_not_local_capture']),
        ('daemon_startup_backfill_summary_logs_repair_hint', moved['daemon_startup_backfill_summary_logs_repair_hint']),
        ('peer_body_size_helper_boundaries', moved['peer_body_size_helper_boundaries']),
        ('send_peer_rejects_oversized_body_before_subprocess', moved['send_peer_rejects_oversized_body_before_subprocess']),
        ('send_peer_watchdog_notice_inf_reports_finite_error_first_at_shim', moved['send_peer_watchdog_notice_inf_reports_finite_error_first_at_shim']),
        ('send_peer_watchdog_notice_zero_still_rejects_request_only_at_shim', moved['send_peer_watchdog_notice_zero_still_rejects_request_only_at_shim']),
        ('send_peer_watchdog_bare_minus_inf_argparse_error_at_shim', moved['send_peer_watchdog_bare_minus_inf_argparse_error_at_shim']),
        ('send_peer_watchdog_equals_minus_inf_reports_finite_error_at_shim', moved['send_peer_watchdog_equals_minus_inf_reports_finite_error_at_shim']),
        ('send_peer_watchdog_finite_value_forwarded_with_equals', moved['send_peer_watchdog_finite_value_forwarded_with_equals']),
        ('send_peer_body_input_diagnostics_are_specific', moved['send_peer_body_input_diagnostics_are_specific']),
        ('send_peer_rejects_split_inline_body', moved['send_peer_rejects_split_inline_body']),
        ('send_peer_rejects_implicit_split_inline_body', moved['send_peer_rejects_implicit_split_inline_body']),
        ('send_peer_accepts_option_after_destination_with_stdin', moved['send_peer_accepts_option_after_destination_with_stdin']),
        ('send_peer_accepts_option_after_implicit_target_with_stdin', moved['send_peer_accepts_option_after_implicit_target_with_stdin']),
        ('send_peer_accepts_options_after_destination_before_inline_body', moved['send_peer_accepts_options_after_destination_before_inline_body']),
        ('send_peer_rejects_option_after_inline_body', moved['send_peer_rejects_option_after_inline_body']),
        ('send_peer_rejects_duplicate_destination_after_destination', moved['send_peer_rejects_duplicate_destination_after_destination']),
        ('send_peer_implicit_target_option_without_body_reports_body_required', moved['send_peer_implicit_target_option_without_body_reports_body_required']),
        ('send_peer_rejects_allow_spoof_after_implicit_target', moved['send_peer_rejects_allow_spoof_after_implicit_target']),
        ('send_peer_single_inline_body_uses_stdin_handoff', moved['send_peer_single_inline_body_uses_stdin_handoff']),
        ('send_peer_request_success_prints_anti_wait_hint', moved['send_peer_request_success_prints_anti_wait_hint']),
        ('send_peer_prior_hint_precedes_success_hint', moved['send_peer_prior_hint_precedes_success_hint']),
        ('send_peer_notice_success_prints_alarm_and_anti_wait_hints', moved['send_peer_notice_success_prints_alarm_and_anti_wait_hints']),
        ('send_peer_aggregate_request_success_prints_result_hint', moved['send_peer_aggregate_request_success_prints_result_hint']),
        ('send_peer_subprocess_failure_prints_no_success_hint', moved['send_peer_subprocess_failure_prints_no_success_hint']),
        ('send_peer_ambient_socket_stdin_does_not_block', moved['send_peer_ambient_socket_stdin_does_not_block']),
        ('send_peer_inline_body_accepts_empty_non_tty_stdin', moved['send_peer_inline_body_accepts_empty_non_tty_stdin']),
        ('send_peer_explicit_stdin_multibyte_body', moved['send_peer_explicit_stdin_multibyte_body']),
        ('send_peer_implicit_target_allows_stdin', moved['send_peer_implicit_target_allows_stdin']),
        ('send_peer_implicit_target_resolves_session_from_pane', moved['send_peer_implicit_target_resolves_session_from_pane']),
        ('send_peer_implicit_target_stdin_resolves_session_from_pane', moved['send_peer_implicit_target_stdin_resolves_session_from_pane']),
        ('send_peer_precheck_fails_open_identity_errors_owned_by_validator', moved['send_peer_precheck_fails_open_identity_errors_owned_by_validator']),
        ('send_peer_allow_spoof_requires_explicit_destination_without_session', moved['send_peer_allow_spoof_requires_explicit_destination_without_session']),
        ('send_peer_rejects_allow_spoof_attached_value', moved['send_peer_rejects_allow_spoof_attached_value']),
        ('send_peer_all_rejects_leading_alias_body', moved['send_peer_all_rejects_leading_alias_body']),
        ('send_peer_rejects_stdin_with_positional_body', moved['send_peer_rejects_stdin_with_positional_body']),
        ('send_peer_rejects_pipe_with_positional_body', moved['send_peer_rejects_pipe_with_positional_body']),
        ('send_peer_pipe_only_body_still_supported', moved['send_peer_pipe_only_body_still_supported']),
        ('send_peer_precheck_option_table_matches_parser', moved['send_peer_precheck_option_table_matches_parser']),
        ('enqueue_rejects_body_and_stdin_before_session_lookup', moved['enqueue_rejects_body_and_stdin_before_session_lookup']),
        ('enqueue_rejects_empty_body_and_stdin', moved['enqueue_rejects_empty_body_and_stdin']),
        ('enqueue_rejects_body_and_stdin_argv_order_independent', moved['enqueue_rejects_body_and_stdin_argv_order_independent']),
        ('enqueue_body_only_still_works', moved['enqueue_body_only_still_works']),
        ('enqueue_stdin_only_still_works', moved['enqueue_stdin_only_still_works']),
        ('enqueue_aggregate_stdout_socket_and_fallback', moved['enqueue_aggregate_stdout_socket_and_fallback']),
        ('enqueue_aggregate_stdout_all_and_negative_cases', moved['enqueue_aggregate_stdout_all_and_negative_cases']),
        ('enqueue_bare_body_without_value_remains_argparse_owned', moved['enqueue_bare_body_without_value_remains_argparse_owned']),
        ('enqueue_rejects_oversized_body_unchanged', moved['enqueue_rejects_oversized_body_unchanged']),
        ('enqueue_stdin_rejects_oversized_body_unchanged', moved['enqueue_stdin_rejects_oversized_body_unchanged']),
        ('enqueue_socket_success_hints_stderr_stdout_unchanged', moved['enqueue_socket_success_hints_stderr_stdout_unchanged']),
        ('enqueue_fallback_prior_hint_pending_cancel', moved['enqueue_fallback_prior_hint_pending_cancel']),
        ('enqueue_fallback_prior_hint_submitted_interrupt', moved['enqueue_fallback_prior_hint_submitted_interrupt']),
        ('enqueue_fallback_prior_hint_plain_inflight_omitted', moved['enqueue_fallback_prior_hint_plain_inflight_omitted']),
        ('enqueue_fallback_prior_hint_pane_mode_inflight_cancel', moved['enqueue_fallback_prior_hint_pane_mode_inflight_cancel']),
        ('enqueue_fallback_prior_hint_write_failure_suppresses_hint', moved['enqueue_fallback_prior_hint_write_failure_suppresses_hint']),
        ('enqueue_fallback_response_send_guard_no_hint', moved['enqueue_fallback_response_send_guard_no_hint']),
        ('alarm_cancel_preserves_at_limit_body', moved['alarm_cancel_preserves_at_limit_body']),
        ('prompt_body_preserves_multiline_and_sanitizes', moved['prompt_body_preserves_multiline_and_sanitizes']),
        ('build_peer_prompt_signature_drops_max_hops', moved['build_peer_prompt_signature_drops_max_hops']),
        ('tmux_paste_buffer_delivery_sequence', moved['tmux_paste_buffer_delivery_sequence']),
        ('daemon_logs_body_truncated_for_legacy_long_body', moved['daemon_logs_body_truncated_for_legacy_long_body']),
        ('peer_result_redirect_single_over_limit', moved['peer_result_redirect_single_over_limit']),
        ('peer_result_redirect_restart_queue_roundtrip', moved['peer_result_redirect_restart_queue_roundtrip']),
        ('peer_result_redirect_below_limit_inline', moved['peer_result_redirect_below_limit_inline']),
        ('peer_result_redirect_write_failure_fallback', moved['peer_result_redirect_write_failure_fallback']),
        ('peer_result_redirect_collision_and_symlink_safe', moved['peer_result_redirect_collision_and_symlink_safe']),
        ('peer_result_redirect_share_root_owner_mismatch', moved['peer_result_redirect_share_root_owner_mismatch']),
        ('peer_result_redirect_replies_permission_drift_tightened', moved['peer_result_redirect_replies_permission_drift_tightened']),
        ('peer_result_redirect_logs_reduced_preview_chars', moved['peer_result_redirect_logs_reduced_preview_chars']),
        ('peer_result_redirect_malformed_message_id_safe_filename', moved['peer_result_redirect_malformed_message_id_safe_filename']),
        ('peer_result_redirect_aggregate_unique_once', moved['peer_result_redirect_aggregate_unique_once']),
        ('response_send_guard_socket_cli_error_kind', moved['response_send_guard_socket_cli_error_kind']),
        ('response_send_guard_socket_error_kind_parse', moved['response_send_guard_socket_error_kind_parse']),
        ('enqueue_fallback_success_silent_with_raw_diagnostic', moved['enqueue_fallback_success_silent_with_raw_diagnostic']),
        ('enqueue_fallback_write_failure_preserves_stderr', moved['enqueue_fallback_write_failure_preserves_stderr']),
        ('response_send_guard_fallback_blocks_unchanged', moved['response_send_guard_fallback_blocks_unchanged']),
        ('response_send_guard_fallback_all_blocks_unchanged', moved['response_send_guard_fallback_all_blocks_unchanged']),
        ('response_send_guard_fallback_partial_blocks_unchanged', moved['response_send_guard_fallback_partial_blocks_unchanged']),
        ('response_send_guard_fallback_force_allows', moved['response_send_guard_fallback_force_allows']),
        ('response_send_guard_fallback_no_auto_return_allowed', moved['response_send_guard_fallback_no_auto_return_allowed']),
        ('response_send_guard_fallback_false_positive_resistance', moved['response_send_guard_fallback_false_positive_resistance']),
        ('clear_reservation_blocks_delivery', moved['clear_reservation_blocks_delivery']),
        ('clear_guard_formatter_force_guidance', moved['clear_guard_formatter_force_guidance']),
        ('clear_guard_force_truth_matches_policy', moved['clear_guard_force_truth_matches_policy']),
        ('clear_single_guard_reads_aggregates_outside_state_lock', moved['clear_single_guard_reads_aggregates_outside_state_lock']),
        ('clear_multi_guard_reads_aggregates_outside_state_lock', moved['clear_multi_guard_reads_aggregates_outside_state_lock']),
        ('clear_multi_guard_pass_reserves_all', moved['clear_multi_guard_pass_reserves_all']),
        ('clear_multi_guard_hard_blocker_rejects_all', moved['clear_multi_guard_hard_blocker_rejects_all']),
        ('clear_multi_guard_soft_blocker_rejects_all', moved['clear_multi_guard_soft_blocker_rejects_all']),
        ('clear_multi_partial_outcomes_and_cleanup', moved['clear_multi_partial_outcomes_and_cleanup']),
        ('clear_multi_pre_pane_failure_continues', moved['clear_multi_pre_pane_failure_continues']),
        ('clear_multi_forced_leave_notice_waits_behind_reservation', moved['clear_multi_forced_leave_notice_waits_behind_reservation']),
        ('clear_multi_lock_wait_failed_and_rerun', moved['clear_multi_lock_wait_failed_and_rerun']),
        ('clear_multi_real_post_touch_exception_forces_leave', moved['clear_multi_real_post_touch_exception_forces_leave']),
        ('clear_multi_real_success_holds_until_batch_end', moved['clear_multi_real_success_holds_until_batch_end']),
        ('clear_multi_real_pre_pane_failure_holds_until_batch_end', moved['clear_multi_real_pre_pane_failure_holds_until_batch_end']),
        ('clear_guard_blocks_pending_self_clear', moved['clear_guard_blocks_pending_self_clear']),
        ('clear_guard_uses_watchdog_snapshot_for_target_alarms', moved['clear_guard_uses_watchdog_snapshot_for_target_alarms']),
        ('clear_multi_daemon_validation', moved['clear_multi_daemon_validation']),
        ('clear_peer_cli_multi_and_compatibility', moved['clear_peer_cli_multi_and_compatibility']),
        ('clear_multi_timeout_and_formatter', moved['clear_multi_timeout_and_formatter']),
        ('self_clear_force_guidance_and_preserved_force', moved['self_clear_force_guidance_and_preserved_force']),
        ('requester_cleared_prompt_guard_and_notice', moved['requester_cleared_prompt_guard_and_notice']),
        ('clear_marker_routes_fast_stop', moved['clear_marker_routes_fast_stop']),
        ('clear_marker_probe_id_fallback_contracts', moved['clear_marker_probe_id_fallback_contracts']),
        ('clear_post_clear_first_request_routes_reply', moved['clear_post_clear_first_request_routes_reply']),
        ('clear_with_existing_inbound_queue_routes_replies', moved['clear_with_existing_inbound_queue_routes_replies']),
        ('clear_file_fallback_blocked_sender_aged_ingress', moved['clear_file_fallback_blocked_sender_aged_ingress']),
        ('clear_post_clear_delay_config_and_settle', moved['clear_post_clear_delay_config_and_settle']),
        ('clear_settle_pane_not_ready_forces_leave', moved['clear_settle_pane_not_ready_forces_leave']),
        ('clear_identity_helper_preserves_verified_live_identity', moved['clear_identity_helper_preserves_verified_live_identity']),
        ('clear_requires_verified_process_identity', moved['clear_requires_verified_process_identity']),
        ('clear_codex_post_clear_endpoint_verify_immediately', moved['clear_codex_post_clear_endpoint_verify_immediately']),
        ('clear_claude_post_clear_probe_pasted_and_completes', moved['clear_claude_post_clear_probe_pasted_and_completes']),
        ('clear_session_end_suppression_is_exact', moved['clear_session_end_suppression_is_exact']),
        ('command_state_lock_timeout_before_mutation', moved['command_state_lock_timeout_before_mutation']),
        ('alarm_registration_split_from_state_lock', moved['alarm_registration_split_from_state_lock']),
        ('clear_success_delivery_defers_near_deadline', moved['clear_success_delivery_defers_near_deadline']),
        ('clear_success_delivery_lock_wait_does_not_fail_after_commit', moved['clear_success_delivery_lock_wait_does_not_fail_after_commit']),
        ('clear_waits_for_same_target_delivery_touch', moved['clear_waits_for_same_target_delivery_touch']),
        ('clear_probe_subprocess_timeouts', moved['clear_probe_subprocess_timeouts']),
        ('clear_marker_phase2_missing_forces_leave', moved['clear_marker_phase2_missing_forces_leave']),
        ('clear_prompt_force_leave_drains_aggregate_after_lock', moved['clear_prompt_force_leave_drains_aggregate_after_lock']),
        ('clear_marker_phase2_rejects_record_turn_without_marker_turn', moved['clear_marker_phase2_rejects_record_turn_without_marker_turn']),
        ('run_clear_peer_phase2_failure_returns_immediately', moved['run_clear_peer_phase2_failure_returns_immediately']),
        ('clear_force_leave_cleans_identity_stores', moved['clear_force_leave_cleans_identity_stores']),
        ('clear_force_leave_unowned_lock_serializes_cleanup', moved['clear_force_leave_unowned_lock_serializes_cleanup']),
        ('clear_identity_helper_success_and_failure', moved['clear_identity_helper_success_and_failure']),
        ('force_clear_requester_dual_write_queue_and_active', moved['force_clear_requester_dual_write_queue_and_active']),
        ('force_clear_aggregate_invalidation_survives_probe_failure', moved['force_clear_aggregate_invalidation_survives_probe_failure']),
        ('clear_aggregate_requester_late_reply_suppressed', moved['clear_aggregate_requester_late_reply_suppressed']),
        ('self_clear_promotion_and_cancel_notice_ordering', moved['self_clear_promotion_and_cancel_notice_ordering']),
        ('clear_marker_ttl_expiry_removes_marker', moved['clear_marker_ttl_expiry_removes_marker']),
    ]

def _validate_scenarios(scenarios: Sequence[Scenario]) -> None:
    labels: set[str] = set()
    functions: set[ScenarioFn] = set()
    duplicate_labels: list[str] = []
    duplicate_functions: list[str] = []

    for entry in scenarios:
        if not isinstance(entry, tuple) or len(entry) != 2:
            raise ValueError(f"invalid scenario entry: {entry!r}")
        label, fn = entry
        if not isinstance(label, str) or not label:
            raise ValueError(f"invalid scenario label: {label!r}")
        if not callable(fn):
            raise ValueError(f"scenario {label!r} is not callable: {fn!r}")
        if label in labels:
            duplicate_labels.append(label)
        labels.add(label)
        if fn in functions:
            duplicate_functions.append(getattr(fn, "__name__", repr(fn)))
        functions.add(fn)

    if duplicate_labels:
        raise ValueError(f"duplicate scenario labels: {', '.join(duplicate_labels)}")
    if duplicate_functions:
        raise ValueError(f"duplicate scenario functions: {', '.join(duplicate_functions)}")
